{
  "guild": {
    "id": "774897545717219328",
    "name": "Genie Community",
    "iconUrl": "https://cdn.discordapp.com/icons/774897545717219328/37e348a8a0b2b83ce9241942f0b9a8b5.png?size=512"
  },
  "channel": {
    "id": "1158048152104992769",
    "type": "GuildPublicThread",
    "categoryId": "1032309299512344626",
    "category": "help-forum",
    "name": "Mac OS issues with launching Genie app",
    "topic": null
  },
  "dateRange": {
    "after": null,
    "before": null
  },
  "exportedAt": "2023-10-17T19:21:34.4500403+00:00",
  "messages": [
    {
      "id": "1158048152104992769",
      "type": "Default",
      "timestamp": "2023-10-01T14:29:54.956+00:00",
      "timestampEdited": null,
      "callEndedTimestamp": null,
      "isPinned": false,
      "content": "I am having trouble working with Genie on Mac OS (Apple M1 sillicon chip). The default app loads in my browser, but the VS Code extension never allows me into design mode and I see a ton of errors in my console:\n\nAny ideas? I tried restarting the app numerous times. Also completely removed it and created a new one to no avail.",
      "author": {
        "id": "1039991814020677673",
        "name": "tradingnirvana",
        "discriminator": "0000",
        "nickname": "TradingNirvana",
        "color": null,
        "isBot": false,
        "roles": [],
        "avatarUrl": "https://cdn.discordapp.com/avatars/1039991814020677673/95e8a38c06c80d3def4ef9ec9f15687f.png?size=512"
      },
      "attachments": [
        {
          "id": "1158048152784490497",
          "url": "https://cdn.discordapp.com/attachments/1158048152104992769/1158048152784490497/message.txt?ex=653e6c63&is=652bf763&hm=f998eb535a9c9a9e1be92ee20b020c0441b07f06170efb6a97d85fc4f1cd74c8&",
          "fileName": "message.txt",
          "fileSizeBytes": 21858
        }
      ],
      "embeds": [],
      "stickers": [],
      "reactions": [],
      "mentions": []
    },
    {
      "id": "1158123435390677112",
      "type": "Default",
      "timestamp": "2023-10-01T19:29:03.89+00:00",
      "timestampEdited": null,
      "callEndedTimestamp": null,
      "isPinned": false,
      "content": "As an update, it now runs, although the Router errors still show up. It's annoying, but it is what it is.",
      "author": {
        "id": "1039991814020677673",
        "name": "tradingnirvana",
        "discriminator": "0000",
        "nickname": "TradingNirvana",
        "color": null,
        "isBot": false,
        "roles": [],
        "avatarUrl": "https://cdn.discordapp.com/avatars/1039991814020677673/95e8a38c06c80d3def4ef9ec9f15687f.png?size=512"
      },
      "attachments": [],
      "embeds": [],
      "stickers": [],
      "reactions": [],
      "mentions": []
    },
    {
      "id": "1158405806375567381",
      "type": "Default",
      "timestamp": "2023-10-02T14:11:06.379+00:00",
      "timestampEdited": null,
      "callEndedTimestamp": null,
      "isPinned": false,
      "content": "I've also encountered this bug. I've opened an issue about it\n\nhttps://github.com/GenieFramework/GenieBuilder_GenieCloud_Issues/issues/16",
      "author": {
        "id": "743412727464067154",
        "name": "pere_g",
        "discriminator": "0000",
        "nickname": "Pere",
        "color": "#71DAFF",
        "isBot": false,
        "roles": [
          {
            "id": "1007312585995071698",
            "name": "GENIE TEAM",
            "color": "#71DAFF",
            "position": 8
          },
          {
            "id": "1032698093654777886",
            "name": "Data Science Advocate",
            "color": "#E91E63",
            "position": 5
          }
        ],
        "avatarUrl": "https://cdn.discordapp.com/avatars/743412727464067154/bc30abeb49653e9978c0f7c90f4486a8.png?size=512"
      },
      "attachments": [],
      "embeds": [
        {
          "title": "Launching Genie app returns BoundsError · Issue #16 · GenieFramewor...",
          "url": "https://github.com/GenieFramework/GenieBuilder_GenieCloud_Issues/issues/16",
          "timestamp": null,
          "description": "With a clean environment, creating a new app and launching it returns a BoundsError. This has also been reported by another Discord user I'm on macOS 13.9, Julia 1.9.3, and GenieFramework 1.22 ...",
          "color": "#1E2327",
          "thumbnail": {
            "url": "https://images-ext-1.discordapp.net/external/8-dlzdchDx5NdM1T_VCAFe4x-nwJCMVZBXOufTV-8UA/https/opengraph.githubassets.com/afa73b145c42260189e36e70bb330cfd6f9debd90038044e5b0a525194d25e39/GenieFramework/GenieBuilder_GenieCloud_Issues/issues/16",
            "width": 1200,
            "height": 600
          },
          "images": [],
          "fields": []
        }
      ],
      "stickers": [],
      "reactions": [
        {
          "emoji": {
            "id": "",
            "name": "\uD83D\uDE4F",
            "code": "pray",
            "isAnimated": false,
            "imageUrl": "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/1f64f.svg"
          },
          "count": 1,
          "users": [
            {
              "id": "1039991814020677673",
              "name": "tradingnirvana",
              "discriminator": "0000",
              "nickname": "TradingNirvana",
              "isBot": false,
              "avatarUrl": "https://cdn.discordapp.com/avatars/1039991814020677673/95e8a38c06c80d3def4ef9ec9f15687f.png?size=512"
            }
          ]
        },
        {
          "emoji": {
            "id": "",
            "name": "✅",
            "code": "white_check_mark",
            "isAnimated": false,
            "imageUrl": "https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/2705.svg"
          },
          "count": 1,
          "users": [
            {
              "id": "743412727464067154",
              "name": "pere_g",
              "discriminator": "0000",
              "nickname": "Pere",
              "isBot": false,
              "avatarUrl": "https://cdn.discordapp.com/avatars/743412727464067154/bc30abeb49653e9978c0f7c90f4486a8.png?size=512"
            }
          ]
        }
      ],
      "mentions": []
    }
  ],
  "messageCount": 3
}